Add opt support
PaddlePaddle/X2Paddle pull request #681
Opened 2021-09-27 09:00 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contributes
1、将opt工具集成到X2Paddle，可一键转换为Paddle-Lite支持格式
2、添加API文档

2021-09-27 09:25 UTC, jiangjiajun requested changes

2021-09-27 09:25 UTC, jiangjiajun commented on README.md
>  | --define_input_shape | **[可选]** For TensorFlow, 当指定该参数时，强制用户输入每个Placeholder的shape，见[文档Q2](./docs/inference_model_convertor/FAQ.md) |
命令行也得加

2021-09-27 09:25 UTC, jiangjiajun commented on README.md
>  项目转换包括3个步骤
不要有链接，而是用相对路径

2021-09-27 09:25 UTC, jiangjiajun commented on docs/inference_model_convertor/api.md
> +x2paddle.convert.caffe2paddle(proto, weight, save_dir, caffe_proto, convert_opt=False, valid_places="arm", model_type="naive_buffer")
参数名改下吧，proto_file, weight_file，另外这里这个caffe_proto要怎么填？是个必选参数？

2021-09-27 09:25 UTC, jiangjiajun commented on docs/inference_model_convertor/api.md
> +x2paddle.convert.caffe2paddle(proto, weight, save_dir, caffe_proto, convert_opt=False, valid_places="arm", model_type="naive_buffer")
convert_opt建议改成convert_to_lite，写成opt看不懂参数是什么意思， 后面两个参数也对应改成lite_valid_palces(这里命名是places，但为什么不是一个list)， model_type也改成lite_model_type

2021-09-27 09:25 UTC, jiangjiajun commented on x2paddle/convert.py
> +    if convert_opt:
这段代码统一成一个函数，给几个小函数调用吧，重复的代码会提高维护的成本

2021-09-28 06:56 UTC, wjj19950828 commented on README.md
>  | --define_input_shape | **[可选]** For TensorFlow, 当指定该参数时，强制用户输入每个Placeholder的shape，见[文档Q2](./docs/inference_model_convertor/FAQ.md) |
Done.

2021-09-28 06:56 UTC, wjj19950828 commented on README.md
>  项目转换包括3个步骤
Done

2021-09-28 07:03 UTC, wjj19950828 commented on docs/inference_model_convertor/api.md
> +x2paddle.convert.caffe2paddle(proto, weight, save_dir, caffe_proto, convert_opt=False, valid_places="arm", model_type="naive_buffer")
Done. 
caffe_proto为一个选填项，表示caffe.proto编译成caffe_pb2.py文件的存放路径，当存在自定义Layer时使用。
lite_valid_palces可以同时指定多个backend(以逗号分隔)，例如“arm,npu”，opt将会自动选择最佳方式。这些在文档都已提及

2021-09-28 07:03 UTC, wjj19950828 commented on x2paddle/convert.py
> +    if convert_opt:
Done.

2021-09-28 07:36 UTC, jiangjiajun commented on docs/inference_model_convertor/convert2lite_api.md
> +# save_dir(str)为转换后模型保存路径
参数名跟tf, caffe的不一样，另外注释也要保持相同

2021-09-28 07:50 UTC, wjj19950828 commented on docs/inference_model_convertor/convert2lite_api.md
> +# save_dir(str)为转换后模型保存路径
Done.

2021-10-05 06:36 UTC, merged