Add SiLU op for PyTorch
PaddlePaddle/X2Paddle pull request #696
Opened 2021-11-08 08:23 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contributes
1、add aten::silu op for PyTorch

2021-11-28 11:48 UTC, jiangjiajun requested changes

2021-11-28 11:48 UTC, jiangjiajun commented on x2paddle/op_mapper/pytorch2paddle/aten.py
> +def aten_silu_(mapper, graph, node):
这里两个函数代码看起来类似，是否可以合并起来

2021-11-29 08:36 UTC, wjj19950828 commented on x2paddle/op_mapper/pytorch2paddle/aten.py
> +def aten_silu_(mapper, graph, node):
TorchScript中会出现这种情况：aten::relu和aten::relu_，这种名字不同但是功能一致的op，之前的逻辑是在添加一个convert函数，复用aten_relu的代码，现在添加判断逻辑，aten::relu和aten::relu_共用aten_relu()这个function

2021-11-30 13:06 UTC, jiangjiajun requested changes

2021-11-30 13:06 UTC, jiangjiajun commented on x2paddle/convert.py
> +                   code_optimizer=True,
改下，命名改成动+名， 这里改成 enable_code_optim

2021-11-30 13:06 UTC, jiangjiajun commented on x2paddle/core/program.py
> +    def gen_model(self, save_dir, jit_type=None, code_optimizer=True):
同上

2021-11-30 13:27 UTC, wjj19950828 commented on x2paddle/convert.py
> +                   code_optimizer=True,
Done.

2021-11-30 13:27 UTC, wjj19950828 commented on x2paddle/core/program.py
> +    def gen_model(self, save_dir, jit_type=None, code_optimizer=True):
Done.

2021-12-02 06:37 UTC, merged