Version warning
PaddlePaddle/X2Paddle pull request #708
Opened 2021-11-24 09:03 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

2021-11-24 09:20 UTC, jiangjiajun requested changes

2021-11-24 09:20 UTC, jiangjiajun commented on x2paddle/convert.py
>              return
- 删除上面的print
- 版本号3位都判断，不写临时性的代码

2021-11-24 09:20 UTC, jiangjiajun commented on x2paddle/convert.py
>              return
print改用logging.info, warning也同样改，避免用print

2021-11-24 12:34 UTC, wjj19950828 commented on x2paddle/convert.py
>              return
Done.

2021-11-25 11:33 UTC, jiangjiajun requested changes

2021-11-25 11:33 UTC, jiangjiajun commented on x2paddle/convert.py
>              return
pytorch>=1.5.0 is required改一下，避免出现
1. 用户低版本，被提示后，直接升级最新版
2. 升级最新版，又提示建议使用1.6.0

因此这里改成“PyTorch版本需要高于1.5.0，1.6.0最推荐这样”

2021-11-26 02:42 UTC, wjj19950828 commented on x2paddle/convert.py
>              return
Done.

2021-11-28 01:56 UTC, jiangjiajun approved these changes

2021-11-28 01:56 UTC, merged