fix onnx convert
PaddlePaddle/X2Paddle pull request #723
Opened 2021-12-22 11:46 UTC by yeliang2258

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  
1. Add Sin、Neg、SpaceToDepth and Cos
2. Fix Upsample、gather and Slice
3. Fix _rename_or_remove_weight

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

2022-01-05 11:21 UTC, jiangjiajun requested changes

2022-01-05 11:21 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +            "paddle.multiply",
为啥不能直接用paddle.neg

2022-01-05 11:43 UTC, yeliang2258 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +            "paddle.multiply",
done

2022-01-07 05:06 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +    data = weights[origin_name]
这个remove逻辑删除的原因是？

2022-01-07 06:03 UTC, yeliang2258 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +    data = weights[origin_name]
一个权重可能作为多个算子的输入，不能一个算子之后直接将权重pop出来

2022-01-07 07:37 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +    data = weights[origin_name]
如若不删除这个weights，会有什么影响，是否会导致转换后的inference模型更大

2022-01-10 11:55 UTC, yeliang2258 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +    data = weights[origin_name]
done，改回去了

2022-01-10 13:05 UTC, yeliang2258 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +            "paddle.multiply",
其实paddle.neg是paddle 2.2之后才有的API，新增了一个判断，2.2之后使用paddle.neg，否则还是-1来乘。

2022-01-11 01:58 UTC, jiangjiajun approved these changes

2022-01-11 04:27 UTC, merged