Fixed SpaceToBatchND、BatchToSpaceND bug
PaddlePaddle/X2Paddle pull request #738
Opened 2022-01-20 10:17 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contributes
1、Fixed SpaceToBatchND、BatchToSpaceND bug
2、solved for https://github.com/PaddlePaddle/X2Paddle/issues/734

2022-01-20 11:16 UTC, jiangjiajun requested changes

2022-01-20 11:16 UTC, jiangjiajun commented on x2paddle/op_mapper/tf2paddle/tf_op_mapper.py
> +            data_format=string('NHWC'))
不支持NHWC，添加transpose解决

2022-01-20 12:31 UTC, wjj19950828 commented on x2paddle/op_mapper/tf2paddle/tf_op_mapper.py
> +            data_format=string('NHWC'))
Done.增加transpose解决

2022-01-21 02:16 UTC, jiangjiajun approved these changes

2022-01-21 02:29 UTC, merged