Add convert states statistics
PaddlePaddle/X2Paddle pull request #766
Opened 2022-03-28 13:08 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contributes
1、添加转换记录统计(PaddleHub)
2、各参数含义：
```convert_state="Start"```代表开始转换到Paddle模型
```convert_state="Success"```代表成功转换到Paddle模型
```lite_state="Start"```代表开始使用一键转换Lite工具
```lite_state="Success"```代表成功转换到Paddle Lite格式

2022-03-29 06:39 UTC, jiangjiajun requested changes

2022-03-29 06:39 UTC, jiangjiajun commented on README.md
> +| --disable_feedback   | **[可选]** 是否关闭用户信息反馈，包括转换框架信息、是否转换成功以及用户ip等，默认为False |
是否关闭X2Paddle使用反馈；X2Paddle默认会统计用户在进行模型转换时的成功率，以及转换框架来源等信息，以便于帮忙X2Paddle根据用户需求进行迭代，不会上传用户的模型文件。如若不想参与反馈，可指定此参数为False即可。

2022-03-29 06:39 UTC, jiangjiajun commented on x2paddle/convert.py
> +        help="Turn off user info feedback")
Tune off feedback of model conversion. 我们收集的是模型转换信息，而非用户信息，描述不要带来误导

2022-03-29 06:39 UTC, jiangjiajun commented on x2paddle/utils.py
> +            requests.get(stats_api, params)
request的get，如若无网络，或者连接慢，这里会卡多久？

2022-03-29 06:39 UTC, jiangjiajun commented on x2paddle/utils.py
> +        self._hash_flag = _md5(str(uuid.uuid1())[-12:]) + "-" + str(
与模型无关的信息，不作收集。x2paddle中不收集用户的信息

2022-03-29 06:39 UTC, jiangjiajun commented on README.md
> +| --disable_feedback   | **[可选]** 是否关闭用户信息反馈，包括转换框架信息、是否转换成功以及用户ip等，默认为False |
另外x2paddle不会去收集用户的信息

2022-03-29 07:29 UTC, wjj19950828 commented on README.md
> +| --disable_feedback   | **[可选]** 是否关闭用户信息反馈，包括转换框架信息、是否转换成功以及用户ip等，默认为False |
Done.

2022-03-29 07:29 UTC, wjj19950828 commented on x2paddle/convert.py
> +        help="Turn off user info feedback")
Done.

2022-03-29 07:30 UTC, wjj19950828 commented on x2paddle/utils.py
> +            requests.get(stats_api, params)
添加timeout=2，也就是2s，Done.

2022-03-29 07:30 UTC, wjj19950828 commented on x2paddle/utils.py
> +        self._hash_flag = _md5(str(uuid.uuid1())[-12:]) + "-" + str(
Done.

2022-04-02 06:13 UTC, KPatr1ck approved these changes
LGTM

2022-04-02 11:06 UTC, jiangjiajun approved these changes

2022-04-04 09:01 UTC, jiangjiajun requested changes

2022-04-04 09:01 UTC, jiangjiajun commented on setup.py
为什么需要移除

2022-04-04 12:51 UTC, wjj19950828 commented on setup.py
一开始发现若将pandas加入依赖，在运行```python setup.py install```会手动编译pandas，导致安装时间很长（5～10分钟），如下图：
<img width="995" alt="50ac5b1ce0fa8c0d5488b8b99138a9cf" src="https://user-images.githubusercontent.com/19977378/161547472-aceee7df-5ba2-48ca-8ef2-84c0eec1a2d8.png">

后将pandas指定为较低版本解决，Done.

2022-04-06 02:42 UTC, jiangjiajun commented on setup.py
我看了下代码，pandas是转pytorch时才需要的依赖，所以直接移出吧

2022-04-06 02:58 UTC, wjj19950828 commented on setup.py
Done.

2022-04-06 03:02 UTC, jiangjiajun commented on setup.py
treelib也是，都删了吧

2022-04-06 03:38 UTC, wjj19950828 commented on setup.py
Done.

2022-04-06 03:48 UTC, jiangjiajun approved these changes

2022-04-07 08:40 UTC, merged