Add aten::linear
PaddlePaddle/X2Paddle pull request #769
Opened 2022-04-11 06:54 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

2022-04-12 02:15 UTC, jiangjiajun approved these changes

2022-04-27 11:11 UTC, jiangjiajun requested changes

2022-04-27 11:11 UTC, jiangjiajun commented on x2paddle/op_mapper/pytorch2paddle/aten.py
> +    layer_inputs["weight"] = inputs_name[1] + "_transpose"
为啥要做transpose呢。 另外如果是transpose, 这里的weight是一个权重parameter吗，是否可以提前预处理好，而不是引入新的transpose操作

2022-04-27 11:26 UTC, wjj19950828 commented on x2paddle/op_mapper/pytorch2paddle/aten.py
> +    layer_inputs["weight"] = inputs_name[1] + "_transpose"
transpose是因为torch和paddle对于weight的shape不同导致

torch的weight：shape是[out_features, in_features]
https://pytorch.org/docs/stable/generated/torch.nn.functional.linear.html?highlight=linear#torch.nn.functional.linear

paddle的weight：shape是[in_features, out_features]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/linear_cn.html#linear

然后这里的weight是一个输入，非权重，所以也没办法预处理好

2022-04-28 02:40 UTC, merged