Support ONNX Roberta model
PaddlePaddle/X2Paddle pull request #793
Opened 2022-05-10 08:03 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contribues
1、新增```CumSum``` op
2、支持ONNX Roberta模型

2022-05-10 11:00 UTC, jiangjiajun requested changes

2022-05-10 11:00 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +        axis_values = _const_weight_or_none(axis)
这个const_weight_or_none是指会返回None的结果吗，需要特殊处理为None的情况吗

2022-05-11 07:04 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +        axis_values = _const_weight_or_none(axis)
Done.若得到的值为None直接assert掉

2022-05-11 07:55 UTC, jiangjiajun approved these changes

2022-05-11 10:41 UTC, merged