Support T5 Model
PaddlePaddle/X2Paddle pull request #794
Opened 2022-05-11 12:49 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contributes
1、新增op：LessOrEqual
2、修复Unsqueeze、MatMul op：
- Unsqueeze为之前的[条件判断](https://github.com/PaddlePaddle/X2Paddle/blob/develop/x2paddle/op_mapper/onnx2paddle/opset9/opset.py#L744]):axes为一个node，需获取node里的value才能进行判断
- MatMul为```x_shape```或者```y_shape```可能为空导致x_shape[0]报错，增加不为空条件

3、重写Gather逻辑，具体如下：
a、首先判断```indices```的shape是否为1D，若为1D，则直接调用```paddle.gather```
b、若```indices```的shape不为1D：
- axis为0且输入类型为DataNode，用```paddle.nn.Embedding```替代gather
- 其他情况则将indice的shape变成1D，gather之后再reshape回对应大小（若shape获取不到，则用shape_tensor + slice解决）

4、去掉重复```GatherND```代码

2022-05-12 06:32 UTC, jiangjiajun requested changes

2022-05-12 06:32 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +            axes = _const_weight_or_none(axes)
上面判断了是否axes为None, 下面又调用了一个可能返回为None的函数，这个需要给一个方案来解决，要么这个函数是否不能返回为None

2022-05-12 06:32 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +            if isinstance(axes, list) or isinstance(axes, tuple) or isinstance(
改成isinstance(axes, (list, tuple, np.ndarray))这样会更简洁点

2022-05-12 06:32 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +        indices_values = _const_weight_or_none(indices)
同上

2022-05-12 07:58 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +            axes = _const_weight_or_none(axes)
Done.
之前实现是因为ONNX版本不同判断axes是Node的一个属性还是输入，若是输入再用```_const_weight_or_none```获取value

目前修改逻辑，因为```paddle.unsqueeze```支持```axes```为一个Tensor，所以按如下逻辑判断：
- 若```axes```为一个属性，直接获取属性值
- 若```axes```为一个输入节点，输入该节点的name

从而去掉```_const_weight_or_none ```函数

2022-05-12 07:59 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +            if isinstance(axes, list) or isinstance(axes, tuple) or isinstance(
Done.重新实现逻辑无此判断条件

2022-05-12 07:59 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +        indices_values = _const_weight_or_none(indices)
Done.加入```necessary=True```条件

2022-05-12 09:33 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +            axes = _const_weight_or_none(axes)
TODO：目前发现一个问题，unsqueeze输入可能有scalar tensor，正在修改，修改后在此更新

2022-05-20 02:21 UTC, jiangjiajun approved these changes

2022-05-25 03:39 UTC, merged