Support gpt2
PaddlePaddle/X2Paddle pull request #796
Opened 2022-05-12 14:13 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contributes
1、修复Slice op，当输入类型为```uint8```时，转为```int32```类型
2、修复```val_x.out_shapes[0]```可能为空导致取index报错，增加不为空条件
3、修复```Squeeze```的axes为输入节点处理，以及处理scalar tensor的条件判断问题

2022-05-20 02:23 UTC, jiangjiajun requested changes

2022-05-20 02:23 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +                dtype=string('int32'))
最终的结果不需要cast回uint8吗

2022-05-26 07:41 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +                dtype=string('int32'))
Done.增加cast回uint8

2022-05-26 13:19 UTC, jiangjiajun approved these changes

2022-05-31 13:39 UTC, merged