Fixed Flatten op
PaddlePaddle/X2Paddle pull request #797
Opened 2022-05-13 08:29 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contributes
1、修复```Flatten```，若获取不到输入的shape，通过shape tensor去解决

2022-05-30 02:50 UTC, jiangjiajun requested changes

2022-05-30 02:50 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +                    shape=val_x.name + "_all_shape")
这个没法直接用paddle.flatten吗

2022-05-30 04:01 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +                    shape=val_x.name + "_all_shape")
ONNX flatten与paddle.flatten定义不一样

ONNX指定axis，输出为2D tensor

Paddle为指定start_axis以及stop_axis，在这个区间变成连续，其他不变

eg:inputs tensor->[1, 2, 3, 4], axis=2

ONNX：outputs->[2, 12]
Paddle: outputs->[2, 3, 4]

2022-05-30 06:03 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +                    shape=val_x.name + "_all_shape")
那是否这样会更简洁
```
a = paddle.flatten(x, start_axis=0, stop_axis=axis)
b = paddle.reshape(a, (0, -1))
```

2022-05-30 07:05 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset9/opset.py
> +                    shape=val_x.name + "_all_shape")
Done

2022-06-01 01:59 UTC, jiangjiajun approved these changes

2022-06-01 02:20 UTC, merged