Remove scale for add
PaddlePaddle/X2Paddle pull request #835
Opened 2022-07-20 03:18 UTC by wjj19950828

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## Do follow contributes
1、当乘数为1时，去掉scale op
2、solve https://github.com/PaddlePaddle/Paddle/issues/44455

2022-07-20 03:21 UTC, jiangjiajun requested changes

2022-07-20 03:21 UTC, jiangjiajun commented on x2paddle/op_mapper/pytorch2paddle/prim2code.py
> +    if layer.attrs["alpha"] == 1:
alpha应该是个float?

2022-07-20 03:55 UTC, wjj19950828 commented on x2paddle/op_mapper/pytorch2paddle/prim2code.py
> +    if layer.attrs["alpha"] == 1:
Done.改为```abs(layer.attrs["alpha"] - 1.) < 1e-6```

2022-07-22 09:02 UTC, jiangjiajun approved these changes

2022-07-22 09:02 UTC, merged