Fix resize and gemm
PaddlePaddle/X2Paddle pull request #847
Opened 2022-07-27 06:36 UTC by qqj1130247885

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

2022-07-28 05:07 UTC, wjj19950828 requested changes

2022-07-28 05:07 UTC, wjj19950828 commented on x2paddle/decoder/onnx_decoder.py
> +                                    node.which_child[nd.name] = idx
这一部分如果跟此PR一样：https://github.com/PaddlePaddle/X2Paddle/pull/842

则需要去掉，无需提交重复代码

2022-07-28 05:07 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset_legacy.py
> +                    val_scales_values = _const_weight_or_none(val_scales)
```val_scales_values```若没用到则去掉

2022-07-28 05:07 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset_legacy.py
> +                "paddle.scale", inputs={"x": val_mm}, outputs=[node.name])
如果```paddle.scale```中alpha值为1，则去掉scale op

2022-08-02 11:44 UTC, qqj1130247885 commented on x2paddle/op_mapper/onnx2paddle/opset_legacy.py
> +                "paddle.scale", inputs={"x": val_mm}, outputs=[node.name])
Done.

2022-08-02 11:45 UTC, qqj1130247885 commented on x2paddle/op_mapper/onnx2paddle/opset_legacy.py
> +                    val_scales_values = _const_weight_or_none(val_scales)
Done.

2022-08-02 11:45 UTC, qqj1130247885 commented on x2paddle/decoder/onnx_decoder.py
> +                                    node.which_child[nd.name] = idx
关掉#842，修改保留在这个PR里了。

2022-08-03 02:40 UTC, wjj19950828 requested changes

2022-08-03 02:40 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset_legacy.py
> +            self.paddle_graph.add_layer(
这里如果scale的alpha为1，是否能去掉scale op呢？

2022-08-03 03:36 UTC, qqj1130247885 commented on x2paddle/op_mapper/onnx2paddle/opset_legacy.py
> +            self.paddle_graph.add_layer(
我尝试在 alpha！=1 的情况下增加scale op, 跑他们那个export_sim.onnx，会转换失败

2022-08-04 12:53 UTC, wjj19950828 approved these changes

2022-08-05 01:04 UTC, jiangjiajun requested changes

2022-08-05 01:04 UTC, jiangjiajun commented on x2paddle/op_mapper/onnx2paddle/opset_legacy.py
> +                        layer_attrs[pd_attr_name] = onnx_attrs[onnx_attr_name]
这里是Reduce操作吗， 在ONNX里面keep_dims如果为0，且是所有axis都reduce的情况下， 出来的shape是[]的一个scalar tensor, 而paddle是为[1]的tensor

2024-07-30 03:01 UTC, closed without merging