Add isinf
PaddlePaddle/X2Paddle pull request #868
Opened 2022-08-10 07:33 UTC by qqj1130247885

# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [ ] Python code style verification
- [ ] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [ ] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [ ] New Model Supported
- [ ] No New Model Supported

## 主要贡献：
1 增加对isinf的单测程序
2 onset10下增加isinf的转换

2022-08-10 11:58 UTC, wjj19950828 requested changes

2022-08-10 11:58 UTC, wjj19950828 commented on x2paddle/op_mapper/onnx2paddle/opset10.py
> +        if node.get_attr('detect_negative') != None or node.get_attr(
如果这两个属性为默认值，非None，这里是否也会raise Exception呢，但默认值是否是支持的呢

2022-08-11 12:01 UTC, qqj1130247885 commented on x2paddle/op_mapper/onnx2paddle/opset10.py
> +        if node.get_attr('detect_negative') != None or node.get_attr(
Done.

2022-08-19 08:30 UTC, wjj19950828 approved these changes

2022-08-19 08:30 UTC, merged